apiVersion: v1
kind: Service
metadata:
  name: wil-playground
  namespace: dev
  annotations:
    argocd.argoproj.io/sync-options: "Prune=false"
spec:
  selector:
    app: wil-playground
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
  type: LoadBalancer

